config/routes.rb
Rails.application.routes.draw do
  root 'results#index'
  get 'results', to: 'results#index'
  get 'search', to: 'results#search'

  get 'login', to: 'login#new'
  post 'login', to: 'login#create'
  delete 'logout', to: 'login#destroy'

  get 'colleges', to: 'colleges#index', as: 'colleges'
  get 'college', to: 'colleges#new'
  post 'college', to: 'colleges#create'
  get 'college/:id/edit', to: 'colleges#edit', as: 'edit_college'
  patch 'college/:id/edit', to: 'colleges#update', as: false
  delete 'college/:id/delete', to: 'colleges#destroy', as: 'delete_college'

  get 'courses', to: 'courses#index'
  get 'course', to: 'courses#new'
  post 'course', to: 'courses#create'
  get 'course/:id/edit', to: 'courses#edit', as: 'edit_course'
  patch 'course/:id/edit', to: 'courses#update', as: false
  delete 'course/:id/delete', to: 'courses#destroy', as: 'delete_course'

  get 'students', to: 'students#index'
  get 'student', to: 'students#new'
  post 'student', to: 'students#create'
  get 'student/:id/edit', to: 'students#edit', as: 'edit_student'
  patch 'student/:id/edit', to: 'students#update', as: false
  delete 'student/:id/delete', to: 'students#destroy', as: 'delete_student'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
  validates_presence_of :name, :city
  validates_inclusion_of :note, :in => 0..5
  validates_uniqueness_of :name

  has_many :courses, dependent: :destroy
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :college
  has_many :students, dependent: :destroy

  validates_presence_of :name, :college
  validates_inclusion_of :note, in: 0..5
  validates :name, uniqueness: { scope: :college_id }

  scope :find_by_name, -> name { where("name ilike ?", name) }

  scope :find_by_college, -> name { joins(:college).where("colleges.name ilike ?", name) }

  scope :ordered_by_general_note, -> {
    joins(:college).order("colleges.note desc")
  }

  # scope :ordered_by_average_students, -> { where()}
  scope :order_by, -> field { order(note: :desc) }

  def average_student_grades
    self.students.present? ? self.students.sum(:note) / self.students.count : 0
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course

  validates_presence_of :name, :course, :document
  validates_uniqueness_of :document
  validates_inclusion_of :note, in: 0..5
  validates :id, uniqueness: {scope: :course_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :name, :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :require_logged_user
  before_action :set_college, only: [:edit, :update, :destroy]

  def index
    @colleges = College.all
  end

  def new
    @college = College.new
  end

  def edit
  end

  def update
    if @college.update(college_params)
      redirect_to colleges_path, notice: t('flash.college.update.notice')
    else
      render :edit
    end
  end

  def destroy
    @college.destroy!
    redirect_to colleges_path, notice: t('flash.college.destroy.notice')
  end

  def create
    @college = College.new(college_params)
    if @college.save
      redirect_to colleges_path, notice: t('flash.college.create.notice')
    else
      render :new
    end
  end

  private

  def college_params
    params.require(:college).permit(:name, :city, :note)
  end

  def set_college
    @college = College.find(params[:id])
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper_method :logged_in?, :current_user
  end

  private

  def redirect_logger_user
    redirect_to colleges_path if logged_in?
  end

  def require_logged_user
    redirect_to login_path, alert: t('flash.must_be_logged_in') unless logged_in?
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_logged_user
  before_action :set_course, only: [:edit, :update, :destroy]
  before_action :set_colleges, only: [:new, :create, :edit, :update]

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to courses_path, notice: t('flash.course.update.notice')
    else
      render :edit
    end
  end

  def destroy
    @course.destroy!
    redirect_to courses_path, notice: t('flash.course.destroy.notice')
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path, notice: t('flash.course.create.notice')
    else
      render :new
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :note, :college_id)
  end

  def set_course
    @course = Course.find(params[:id])
  end

  def set_colleges
    @colleges = College.all
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_action :redirect_logger_user, except: %w[destroy]

  def new
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      reset_session
      session[:user_id] = user.id

      redirect_to colleges_path
    else
      redirect_to login_path, alert: t('flash.login.create.alert')
    end
  end

  def destroy
    reset_session

    redirect_to root_path, alert: t('flash.login.destroy.notice')
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  has_scope :ordered_by_general_note, :default
  has_scope :order_by
  has_scope :find_by_name
  has_scope :find_by_college

  def index
    @results = apply_scopes(Course).all
  end

  def search
    if params[:course_name]
      redirect_to results_path(find_by_name: params[:course_name])
    else
      redirect_to results_path(find_by_college: params[:college_name])
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :require_logged_user
  before_action :set_courses, only: [:new, :create, :edit, :update]
  before_action :set_student, only: [:edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to students_path, notice: t('flash.student.update.notice')
    else
      render :edit
    end
  end

  def destroy
    @student.destroy!
    redirect_to students_path, notice: t('flash.student.destroy.notice')
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path, notice: t('flash.student.create.notice')
    else
      render :new
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :note, :document, :course_id)
  end

  def set_courses
    @courses = Course.all
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/colleges/_form.html.erb
<%= javascript_include_tag 'custom.js' %>

<div class="row">
  <%= form_for college, url: url do |f| %>
    <div class="row">
      <div class="input-field col s6">
        <%= f.text_field :name %>
        <%= f.label :name, t('labels.college.name'), class: "validate" %>
      </div>

      <div class="input-field col s6">
        <%= f.text_field :city %>
        <%= f.label :city, t('labels.college.city') %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s2">
      <%= f.number_field :note, min: 0, max: 5 %>
      <%= f.label :note, t('labels.college.note') %>
      </div>
    </div>

    <div>
      <%= f.submit class: 'btn waves-effect waves-light' %>
    </div>
  <% end %>
</div>

app/views/colleges/edit.html.erb
<h1><%= t('actions.college.edit') %></h1>

<%= render 'layouts/errors', record: @college %>

<%= render 'form', college: @college, url: edit_college_path(@college) %>

<%= link_to t('menu.back'), colleges_path, class: 'btn waves-effect waves-light' %>

app/views/colleges/index.html.erb
<div>
  <p class="flow-text"><%= t('menu.colleges') %></p>
  <%= link_to t('actions.college.create'), college_path, class: 'waves-effect waves-light btn' %>
</div>

<hr/>
<table class="striped">
  <thead>
    <tr>
      <th><%= College.human_attribute_name(:name) %></th>
      <th><%= College.human_attribute_name(:city) %></th>
      <th><%= College.human_attribute_name(:note) %></th>
      <th colspan="2"><%= t('actions.menu_actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= college.city %></td>
        <td><%= college.note %></td>
        <td>
          <%= link_to t('actions.edit'), edit_college_path(college), class: 'btn waves-effect waves-light' %>
          <%= link_to t('actions.delete'), delete_college_path(college), method: 'delete', data: { confirm: t('actions.college.confirm_removal') }, class: 'btn waves-effect waves-light' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/colleges/new.html.erb
<h1><%= t('actions.college.create') %></h1>

<%= render 'layouts/errors', record: @college %>

<%= render 'form', college: @college, url: college_path(@college) %>

<%= link_to t('menu.back'), colleges_path, class: 'btn waves-effect waves-light' %>

app/views/courses/_form.html.erb
<%= javascript_include_tag 'custom.js' %>

<div class="row">
  <%= form_for course, url: url do |f| %>
    <div class="row">
      <div class="input-field col s6">
        <%= f.text_field :name %>
        <%= f.label :name, t('labels.course.name') %>
      </div>

      <div class="input-field col s2">
        <%= f.number_field :note, min: 0, max: 5 %>
        <%= f.label :note, t('labels.course.note') %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= f.select :college_id, options_from_collection_for_select(@colleges, 'id', 'name', f.object.try(:college_id)),  include_blank: true %>

        <%= f.label :college, t('labels.course.college') %>
      </div>
    </div>

    <div>
      <%= f.submit class: 'btn waves-effect waves-light' %>
    </div>
  <% end %>
</div>

app/views/courses/edit.html.erb
<h1><%= t('actions.course.edit') %></h1>

<%= render 'layouts/errors', record: @course %>
<%= render 'form', course: @course, url: edit_course_path(@course) %>

<%= link_to t('menu.back'), courses_path, class: 'btn waves-effect waves-light' %>

app/views/courses/index.html.erb
<div>
  <p class="flow-text"><%= t('menu.courses') %></p>
  <%= link_to t('actions.course.create'), course_path, class: 'waves-effect waves-light btn' %>
</div>

<hr/>
<table class="striped">
  <thead>
    <tr>
      <th><%= Course.human_attribute_name(:name) %></th>
      <th><%= Course.human_attribute_name(:note) %></th>
      <th><%= College.human_attribute_name(:name) %></th>
      <th colspan="2"><%= t('actions.menu_actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.note %></td>
        <td><%= course.college.name %></td>
        <td>
          <%= link_to t('helpers.submit.course.edit'), edit_course_path(course), class: 'btn waves-effect waves-light' %>
          <%= link_to t('helpers.submit.course.delete'), delete_course_path(course), method: 'delete', data: { confirm: t('actions.course.confirm_removal') }, class: 'btn waves-effect waves-light' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1><%= t('actions.course.create') %></h1>

<%= render 'layouts/errors', record: @course %>
<%= render 'form', course: @course, url: course_path(@course) %>

<%= link_to t('menu.back'), courses_path, class: 'btn waves-effect waves-light' %>

app/views/layouts/_errors.html.erb
<% if record.errors.any? %>
  <div class="card-panel red lighten-1">
    <span class="white-text"><%= t('form_error') %></span>
    <ul>
      <% for message in record.errors.full_messages %>
        <li>
          <span class="white-text"><%= message %></span>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollegeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="indigo lighten-1">
      <div class="nav-wrapper container">
        <%= link_to root_path, class: 'brand-logo' do %>
          <i class="medium material-icons">library_books</i>
        <% end %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if logged_in? %>
            <li><%= link_to t('menu.colleges'), colleges_path %></li>
            <li><%= link_to t('menu.courses'), courses_path %></li>
            <li><%= link_to t('menu.students'), students_path %></li>
            <li><%= link_to t('menu.results'), results_path %></li>
            <li><%= link_to t('actions.user.logout'), logout_path, method: 'delete' %></li>
          <% else %>
            <li><%= link_to t('actions.user.login'), login_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |type, message| %>
        <div class="card-panel teal lighten-2">
          <span class="white-text"><%= message %></span>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/login/new.html.erb
<div class="row container">
  <%= form_tag login_path do %>
    <div class="row">
      <div class="input-field col s12">
      <%= label_tag :email, t('labels.user.email') %>
      <%= email_field_tag :email %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= label_tag :password, t('labels.user.password') %>
        <%= password_field_tag :password %>
      </div>
    </div>

    <div>
      <%= submit_tag t('helpers.submit.login'), class: 'btn waves-effect waves-light' %>
    </div>
  <% end %>
</div>

app/views/results/index.html.erb
<div>
  <p class="flow-text"><%= t('menu.results') %></p>
</div>

<div class="row">
  <%= t('menu.search') %>
  <hr/>
  <div class="row">
    <%= link_to t('actions.results.order_by_note'), results_path(order_by: "note"), class: 'btn' %>
    <%= link_to t('actions.results.ordered_by_average_students'), results_path(order_by: "note"), class: 'btn' %>
    <%= link_to t('actions.results.clean'), results_path, class: 'btn' %>
  </div>

  <hr/>
  <div class="row">
    <div class="col s6">
      <%= form_tag search_path, method: :get do %>
        <div class="row">
          <div class="input-field col s6">
            <%= text_field_tag :course_name %>
            <%= label_tag t('labels.result.name') %>
          </div>
        </div>

        <div>
          <%= button_to t('actions.results.find_by_name'), nil, class: "btn" %>
        </div>
      <% end %>
    </div>

    <div class="col s6">
      <%= form_tag search_path, method: :get do %>
        <div class="row">
          <div class="input-field col s6">
            <%= text_field_tag :college_name %>
            <%= label_tag t('labels.result.college_name') %>
          </div>
        </div>

        <div>
          <%= button_to t('actions.results.by_college'), nil, class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<hr/>
<table class="striped">
  <thead>
    <tr>
      <th>Nome do Colegio</th>
      <th>Nome do Curso</th>
      <th>Nota Geral</th>
      <th>Nota do Curso</th>
      <th>Media dos Alunos por Curso</th>
    </tr>
  </thead>
  <tbody>
    <% @results.each do |results| %>
      <tr>
        <td><%= results.college.name %></td>
        <td><%= results.name %></td>
        <td><%= results.college.note %></td>
        <td><%= results.note %></td>
        <td><%= results.average_student_grades %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/_form.html.erb
<%= javascript_include_tag 'custom.js' %>

<div class="row">
  <%= form_for student, url: url do |f| %>
    <div class="row">
      <div class="input-field col s6">
        <%= f.text_field :name %>
        <%= f.label :name, t('labels.student.name') %>
      </div>
      <div class="input-field col s6">
        <%= f.number_field :note, min: 0, max: 10 %>
        <%= f.label :note, t('labels.student.note') %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= f.text_field :document %>
        <%= f.label :document, t('labels.student.document') %>
      </div>
      <div class="input-field col s6">
        <%= f.select :course_id, options_from_collection_for_select(@courses, 'id', 'name', f.object.try(:course_id)), include_blank: true %>
        <%= f.label :course, t('labels.student.course') %>
      </div>
    </div>

    <div>
      <%= f.submit class: 'btn waves-effect waves-ligth' %>
    </div>
  <% end %>
</div>

app/views/students/edit.html.erb
<h1><%= t('actions.student.edit') %></h1>

<%= render 'layouts/errors', record: @student %>
<%= render 'form', student: @student, url: edit_student_path(@student) %>

<%= link_to t('menu.back'), students_path, class: 'btn waves-effect waves-ligth' %>

app/views/students/index.html.erb
<div>
  <p class="flow-text"><%= t('menu.students') %></p>
  <%= link_to t('actions.student.create'), student_path, class: 'waves-effect waves-light btn' %>
</div>

<hr/>
<table class="striped">
  <thead>
    <tr>
      <th><%= Student.human_attribute_name(:name) %></th>
      <th><%= Student.human_attribute_name(:document) %></th>
      <th><%= Student.human_attribute_name(:note) %></th>
      <th><%= Course.human_attribute_name(:name) %></th>
      <th colspan="2"><%= t('actions.menu_actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.document %></td>
        <td><%= student.note %></td>
        <td><%= student.course.name %></td>
        <td>
          <%= link_to t('helpers.submit.student.edit'), edit_student_path(student), class: 'btn waves-effect waves-light' %>
          <%= link_to t('helpers.submit.student.delete'), delete_student_path(student), method: 'delete', data: { confirm: t('actions.student.confirm_removal') }, class: 'btn waves-effect waves-light' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1><%= t('actions.student.create') %></h1>

<%= render 'layouts/errors', record: @student %>
<%= render 'form', student: @student, url: student_path(@student) %>

<%= link_to t('menu.back'), students_path, class: 'btn waves-effect waves-ligth' %>